# Generated by Django 4.2.20 on 2025-03-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
